"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERC721__factory = exports.IFoxPunksMinter__factory = exports.IFoxPunks__factory = exports.IERC2981__factory = exports.IERC1271__factory = exports.FoxPunksMinter__factory = exports.FoxPunks__factory = exports.IERC165__factory = exports.ERC165__factory = exports.IERC721Receiver__factory = exports.IERC721__factory = exports.IERC721Metadata__factory = exports.Ownable__factory = void 0;
var Ownable__factory_1 = require("./factories/Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var IERC721Metadata__factory_1 = require("./factories/IERC721Metadata__factory");
Object.defineProperty(exports, "IERC721Metadata__factory", { enumerable: true, get: function () { return IERC721Metadata__factory_1.IERC721Metadata__factory; } });
var IERC721__factory_1 = require("./factories/IERC721__factory");
Object.defineProperty(exports, "IERC721__factory", { enumerable: true, get: function () { return IERC721__factory_1.IERC721__factory; } });
var IERC721Receiver__factory_1 = require("./factories/IERC721Receiver__factory");
Object.defineProperty(exports, "IERC721Receiver__factory", { enumerable: true, get: function () { return IERC721Receiver__factory_1.IERC721Receiver__factory; } });
var ERC165__factory_1 = require("./factories/ERC165__factory");
Object.defineProperty(exports, "ERC165__factory", { enumerable: true, get: function () { return ERC165__factory_1.ERC165__factory; } });
var IERC165__factory_1 = require("./factories/IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var FoxPunks__factory_1 = require("./factories/FoxPunks__factory");
Object.defineProperty(exports, "FoxPunks__factory", { enumerable: true, get: function () { return FoxPunks__factory_1.FoxPunks__factory; } });
var FoxPunksMinter__factory_1 = require("./factories/FoxPunksMinter__factory");
Object.defineProperty(exports, "FoxPunksMinter__factory", { enumerable: true, get: function () { return FoxPunksMinter__factory_1.FoxPunksMinter__factory; } });
var IERC1271__factory_1 = require("./factories/IERC1271__factory");
Object.defineProperty(exports, "IERC1271__factory", { enumerable: true, get: function () { return IERC1271__factory_1.IERC1271__factory; } });
var IERC2981__factory_1 = require("./factories/IERC2981__factory");
Object.defineProperty(exports, "IERC2981__factory", { enumerable: true, get: function () { return IERC2981__factory_1.IERC2981__factory; } });
var IFoxPunks__factory_1 = require("./factories/IFoxPunks__factory");
Object.defineProperty(exports, "IFoxPunks__factory", { enumerable: true, get: function () { return IFoxPunks__factory_1.IFoxPunks__factory; } });
var IFoxPunksMinter__factory_1 = require("./factories/IFoxPunksMinter__factory");
Object.defineProperty(exports, "IFoxPunksMinter__factory", { enumerable: true, get: function () { return IFoxPunksMinter__factory_1.IFoxPunksMinter__factory; } });
var ERC721__factory_1 = require("./factories/ERC721__factory");
Object.defineProperty(exports, "ERC721__factory", { enumerable: true, get: function () { return ERC721__factory_1.ERC721__factory; } });
//# sourceMappingURL=index.js.map